In [1]:
import os
import pandas as pd
import json
import numpy as np

In [2]:
 !nvidia-smi

/bin/bash: line 1: nvidia-smi: command not found


In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [4]:
os.chdir("/content/drive/MyDrive/toy project")

In [5]:
!dir

datas.zip		     model.pkl
datata.csv		     model.pth
final_inference.py	     price.csv
fine_wordvec.npy	     price_regression_model.ipynb
food_price.ipynb	     reduced_data.csv
food_subtype.csv	     store_region.csv
food_type.csv		     subtype_classification.pickle
food_type_modeling.ipynb     subtype_modeling.ipynb
food_type_m.pkl		     train_datas.csv
ingred_classification.ipynb  train_datas.gsheet
ingred.csv		     valid
modeling.ipynb


In [6]:
subtype = pd.read_csv('food_subtype.csv')

In [7]:
subtype

Unnamed: 0  구이/적  국  기타  김치  떡  만두/떡국  메인요리  면  밥  ...  젓갈  조림  주류  죽  \
0                0     1  0   0   0  0      0     0  0  0  ...   0   0   0  0   
1                1     0  0   0   0  0      0     0  0  0  ...   0   0   1  0   
2                2     1  0   0   0  0      0     0  0  0  ...   0   0   0  0   
3                3     0  0   0   0  0      0     0  0  0  ...   0   0   0  0   
4                4     0  0   0   0  0      0     0  0  0  ...   0   0   1  0   
...            ...   ... ..  ..  .. ..    ...   ... .. ..  ...  ..  ..  .. ..   
732353      732353     0  0   0   0  0      0     0  0  0  ...   0   0   0  0   
732354      732354     0  0   1   0  0      0     0  0  0  ...   0   0   0  0   
732355      732355     0  0   1   0  0      0     0  0  0  ...   0   0   0  0   
732356      732356     0  0   0   0  0      0     0  0  0  ...   0   0   1  0   
732357      732357     0  0   1   0  0      0     0  0  0  ...   0   0   0  0   

        찌개  찜  탕  튀김  한과  회  
0        0  0  0   0   0  0  
1        0  0  0   0   0  0  
2        0  0  0   0   0  0  
3        0  0  0   0   0  0  
4        0  0  0   0   0  0  
...     .. .. ..  ..  .. ..  
732353   0  0  0   1   0  0  
732354   0  0  0   0   0  0  
732355   0  0  0   0   0  0  
732356   0  0  0   0   0  0  
732357   0  0  0   0   0  0  

[732358 rows x 31 columns]

In [8]:
# fasttext
data = np.load('fine_wordvec.npy')

# NumPy 배열을 판다스 데이터프레임으로 변환
data = np.squeeze(data, axis=0)
df = pd.DataFrame(data)
df

0         1         2         3         4         5         6    \
0       0.016328  0.001764  0.025265  0.005606  0.011516  0.021035 -0.034382   
1       0.030902 -0.128914 -0.268103 -0.190439  0.145079  0.014630 -0.055223   
2       0.002485 -0.015088  0.018374 -0.001797 -0.002587 -0.001217  0.002954   
3      -0.003863  0.002732  0.009170 -0.002896 -0.001345  0.003061 -0.009950   
4       0.209347 -0.018021 -0.347191  0.112766 -0.114830  0.085455 -0.160581   
...          ...       ...       ...       ...       ...       ...       ...   
732353  0.023502  0.008115  0.089715  0.046849  0.038653 -0.036225  0.004937   
732354 -0.002007 -0.063415 -0.039640  0.009130  0.040718  0.051164 -0.036447   
732355  0.001328  0.004999  0.019614  0.003473  0.004040 -0.013402  0.002359   
732356 -0.051353 -0.080254 -0.046686 -0.044399  0.040220  0.007978 -0.080835   
732357 -0.004221 -0.002098  0.000584  0.019181  0.003525  0.003279  0.009739   

             7         8         9    ...       290       291       292  \
0       0.023025  0.020524  0.011891  ... -0.001045 -0.007285 -0.006499   
1      -0.060799  0.063615 -0.190054  ...  0.077503  0.322275  0.025965   
2       0.000017 -0.016704 -0.007714  ...  0.005465  0.001118 -0.017413   
3       0.003699 -0.005313  0.008811  ...  0.004269  0.001276 -0.010788   
4      -0.234375  0.268389 -0.214465  ...  0.189539  0.147308 -0.076509   
...          ...       ...       ...  ...       ...       ...       ...   
732353  0.005389 -0.011743  0.043665  ... -0.030008  0.129531 -0.030823   
732354 -0.005281  0.012550  0.018238  ... -0.058260  0.007033  0.023489   
732355 -0.003524 -0.017880 -0.005734  ... -0.006413 -0.003712 -0.009131   
732356 -0.022506  0.149961  0.019359  ...  0.074248 -0.006304 -0.112821   
732357  0.004646 -0.002387  0.012657  ...  0.002918  0.019396 -0.004823   

             293       294       295       296       297       298       299  
0       0.014404  0.009806  0.013958  0.011915 -0.023193  0.009146 -0.009837  
1       0.275712  0.065815 -0.346281  0.052381 -0.166130 -0.079245 -0.093601  
2      -0.005951  0.014729 -0.012800  0.004699 -0.010796 -0.022582  0.003967  
3      -0.005082 -0.010422  0.004980 -0.006807 -0.003329 -0.017083 -0.002277  
4       0.166056  0.239957 -0.272782  0.073746 -0.047802 -0.045509 -0.194227  
...          ...       ...       ...       ...       ...       ...       ...  
732353 -0.082350  0.077706 -0.041368 -0.005917 -0.039728 -0.051169 -0.090568  
732354  0.025581  0.004354 -0.004438  0.011332 -0.062400  0.062635  0.057160  
732355 -0.002901  0.000937  0.012362 -0.000294  0.002548 -0.004867  0.000663  
732356  0.083903 -0.019098 -0.015171  0.195232 -0.024883 -0.063869 -0.120624  
732357 -0.027246  0.022487  0.005228 -0.007939  0.014539 -0.008721  0.001584  

[732358 rows x 300 columns]

## 데이터 전처리

In [9]:
food_subtype = subtype.to_numpy()[:,1:]

In [10]:
food_subtype = np.array([np.argmax(v) for v in food_subtype])

In [11]:
food_subtype[:20]

array([ 0, 22,  0,  9, 22,  8,  0, 22,  7, 22,  8, 14,  2,  2,  1,  1, 25,
        0,  1, 22])

In [20]:
food_subtype


array([ 0, 22,  0, ...,  2, 22,  2])

## 로지스틱 회귀

In [12]:
subtype_input = df.to_numpy()

In [13]:
print(subtype_input[:5])

[[ 0.01632782  0.0017636   0.02526508 ... -0.02319349  0.00914551
  -0.00983702]
 [ 0.03090183 -0.12891386 -0.26810318 ... -0.16612954 -0.0792454
  -0.09360129]
 [ 0.00248452 -0.0150882   0.01837442 ... -0.01079641 -0.02258165
   0.00396666]
 [-0.0038627   0.00273224  0.00917017 ... -0.00332875 -0.01708259
  -0.0022771 ]
 [ 0.2093465  -0.01802051 -0.34719053 ... -0.04780176 -0.04550876
  -0.19422664]]


In [14]:
subtype_target = food_subtype

In [15]:
print(subtype_target[:5])

[ 0 22  0  9 22]


In [16]:
from sklearn.model_selection import train_test_split

train_input, test_input, train_target, test_target = train_test_split(
    subtype_input, subtype_target, test_size = 0.4, random_state=42)

In [17]:
validate_input, test_input, validate_target, test_target = train_test_split(
    test_input, test_target, test_size = 0.5, random_state=42)

In [18]:
# 정규화 전처리
from sklearn.preprocessing import StandardScaler

ss = StandardScaler()
ss.fit(train_input)
train_scaled = ss.transform(train_input)
validate_scaled = ss.transform(validate_input)
test_scaled = ss.transform(test_input)

In [21]:
# 소프트맥스 분류
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(C=10, max_iter=100)
lr.fit(train_scaled, train_target)

print(lr.score(train_scaled, train_target))
print(lr.score(validate_scaled, validate_target))

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.6759684488887473
0.6742653886066962


In [22]:
import pickle

#모델 저장
model = lr

# 모델 저장
with open('food_subtype_m.pkl', 'wb') as model_file:
    pickle.dump(model, model_file)



In [ ]:
lr.score(test_scaled, test_target)

In [ ]:
print(lr.predict(test_scaled[:20]))
print(test_target[:20])


### 하이퍼파라미터 튜닝

In [ ]:
from sklearn.linear_model import LogisticRegression

C_list = [0.01,0.1,1,10,30]
max_iter = [10,30,50,80,100,120,140]

for iter in max_iter:
  for c in C_list:
    lr = LogisticRegression(C=c, max_iter=iter)
    lr.fit(train_scaled, train_target)

    print("C:",c," max_iter : ", iter)
    print(lr.score(train_scaled, train_target))
    print(lr.score(validate_scaled, validate_target))



## 확률적 경사하강법(SGD Classifier)

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
sc = SGDClassifier(loss='log_loss', max_iter=10, random_state=42)
sc.fit(train_scaled, train_target)

print(sc.score(train_scaled, train_target))
print(sc.score(validate_scaled, validate_target))

In [ ]:
sc.partial_fit(train_scaled, train_target)

print(sc.score(train_scaled, train_target))
print(sc.score(test_scaled, test_target))

In [ ]:
import numpy as np

sc = SGDClassifier(loss='log_loss', random_state=42)

train_score = []
test_score = []

classes = np.unique(train_target)

In [ ]:
for i in range(0, 20):
    print(i)
    sc.partial_fit(train_scaled, train_target, classes=classes)

    train_score.append(sc.score(train_scaled, train_target))
    test_score.append(sc.score(test_scaled, test_target))

In [ ]:
import matplotlib.pyplot as plt

plt.plot(train_score)
plt.plot(test_score)
plt.xlabel('epoch')
plt.ylabel('accuracy')
plt.show()

## 결정 트리(Decision Tree)

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=6, random_state=42)
dt.fit(train_scaled, train_target)

print(dt.score(train_scaled, train_target))
print(dt.score(test_scaled, test_target))

0.4473617135548708
0.4480105412638593


## 그레이디언트 부스팅

In [ ]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_validate

gb = GradientBoostingClassifier(n_estimators=10, learning_rate=0.2, random_state=42)
scores = cross_validate(gb, train_input, train_target, return_train_score=True, n_jobs=-1)

print(np.mean(scores['train_score']), np.mean(scores['test_score']))

/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_split.py:700: UserWarning: The least populated class in y has only 3 members, which is less than n_splits=5.
  warnings.warn(
